export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'
export const SET_ERRORS = 'SET_ERRORS'

export const LOAD_TASKS = 'LOAD_TASKS'
export const CREATE_TASK = 'CREATE_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'


export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'

//CONFIRMATION DELETE MESSAGE BOX
export const DISPLAY_DELETE_CONFIRM = 'DELETE_TASK'
export const CLOSE_DELETE_CONFIRM = 'CLOSE_DELETE_CONFIRM'
